# Generated by Django 5.1.5 on 2025-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ideas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="아이디어명")),
                ("photo", models.ImageField(upload_to="", verbose_name="사진")),
                ("description", models.TextField(verbose_name="아이디어 설명")),
                ("interest_rate", models.FloatField(verbose_name="아이디어 관심도")),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("django", "Django"),
                            ("react", "React"),
                            ("flask", "Flask"),
                            ("fastAPI", "Fast ARI"),
                            ("ruby", "Ruby"),
                        ],
                        default="django",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
