# Generated by Django 5.1.5 on 2025-01-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideas",
            name="photo",
            field=models.ImageField(blank=True, upload_to="ideas/", verbose_name="사진"),
        ),
        migrations.AlterField(
            model_name="ideas",
            name="tool",
            field=models.CharField(
                choices=[
                    ("django", "Django"),
                    ("react", "React"),
                    ("flask", "Flask"),
                    ("fastAPI", "Fast ARI"),
                    ("ruby", "Ruby"),
                ],
                default="django",
                max_length=20,
                verbose_name="예상 개발툴",
            ),
        ),
    ]
