# Generated by Django 5.1.5 on 2025-01-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0003_ideas_created_at_ideas_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideas",
            name="is_starred",
            field=models.BooleanField(default=False),
        ),
    ]
