# Generated by Django 5.1.5 on 2025-01-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0004_ideas_is_starred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideas",
            name="tool",
            field=models.CharField(
                choices=[("먄", "먄"), ("ㅁㄴㅇㄹ", "ㅁㄴㅇㄹ")],
                default="django",
                max_length=20,
                verbose_name="예상 개발툴",
            ),
        ),
    ]
