# Generated by Django 5.1.5 on 2025-01-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0006_alter_ideas_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideas",
            name="tool",
            field=models.CharField(
                blank=True,
                choices=[("먄", "먄"), ("ㅁㄴㅇㄹ", "ㅁㄴㅇㄹ")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="예상 개발툴",
            ),
        ),
    ]
