# Generated by Django 5.1.5 on 2025-01-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devTool", "0001_initial"),
        ("ideas", "0007_alter_ideas_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideas",
            name="tool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="devTool.devtool",
                verbose_name="예상 개발툴",
            ),
        ),
    ]
