# Generated by Django 5.1.4 on 2025-01-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("releaseYear", models.IntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "액션"),
                            ("romance", "로맨스"),
                            ("comedy", "코미디"),
                            ("horror", "공포"),
                            ("sci-fi", "SF"),
                        ],
                        default="action",
                        max_length=50,
                    ),
                ),
                ("rating", models.FloatField()),
                ("producer", models.CharField(max_length=255)),
                ("actors", models.TextField()),
                ("runningTime", models.IntegerField()),
                ("review", models.TextField()),
            ],
        ),
    ]
