# Generated by Django 5.1.4 on 2025-01-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="board",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "액션"),
                    ("romance", "로맨스"),
                    ("comedy", "코미디"),
                    ("horror", "공포"),
                    ("sci-fi", "SF"),
                    ("ani", "애니메이션"),
                    ("criticism", "사회비판"),
                ],
                default="action",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="runningTime",
            field=models.TextField(),
        ),
    ]
