# Generated by Django 5.1.4 on 2025-01-10 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_board_image_alter_board_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="image",
        ),
    ]
