# Generated by Django 5.1.5 on 2025-01-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DevTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("kind", models.CharField(max_length=50, verbose_name="종류")),
                ("content", models.TextField(verbose_name="개발 툴 설명")),
            ],
        ),
    ]
